menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/fred1653
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.ico

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65362962-1

# Copyright Infomation
startyear: 2015
